### PR TITLE
Update to Material Design UI

### PR DESCRIPTION
**Pull request by twinone**
See individual commits for info

### CODE REVIEW

**Comment by twinone** [comment]
@zhijiazheng123 What do you think about the look of the app now?

**Comment by zhijiazheng123** [comment]
amazing, you are coding so fast in previous several hours, all done so soon! unbelievable!

**Comment by twinone** [comment]
I had some work done already :)

**Comment by zhijiazheng123** [comment]
so I guess there maybe lots of conflicts comparing to yours and mine, you resolved them and make it work fine efficiently, really appreciate that.

**Pull request merged**
