### PR TITLE
Add material design NavigationView

### PR DESCRIPTION
**Pull request by zhijiazheng123**

### CODE REVIEW

**Comment by zhijiazheng123** [comment]
ready for merge now.

**Comment by twinone** [comment]
Why do you revert the string fix? I get the following message in Android Studio:
Error:The element type "string" must be terminated by the matching end-tag "</string>".

**Comment by zhijiazheng123** [comment]
no, actually I didn't revert it, my code base is a little old, I saw you have resolved this string issue, so I revert mine :)

**Comment by twinone** [comment]
Please make a pull-request for the branch materia-ui which I just created

**Comment by twinone** [comment]
Never mind, I'll merge it

**Comment by twinone** [comment]
Merged into material-ui 22f5f5c515c6c55f60234d1b80f09d97e0b17ba2

**Pull request closed without merging**
