### PR TITLE
Update for NavigationView: Should display under Toolbar

### PR DESCRIPTION
**Pull request by zhijiazheng123**

### CODE REVIEW

**Comment by twinone** [comment]
Uhh, have you tried it out? It looks like this:
screenshot

**Comment by twinone** [comment]
Material Design guidelines state that the NavigationView should take up the whole screen.
I like it more under the Toolbar too, but the whole NavigationView has a padding at the top of 24dp (like the statusbar), so if we put it under the toolbar we have some very ugly padding at the top. That's why I thought of the header.

**Comment by zhijiazheng123** [comment]
that doesn't make sense to me, if it has padding at top of 24dp, why it doesn't have it when taking up the whole screen? BTW my device base on Android4.4 do not have this padding issue.
screenshot_2015-07-30-17-21-30

**Comment by twinone** [comment]
You're right. There's no padding when using header. But when the NavigationView is under the Toolbar, the header looks really stupid, but when you set header="@null", the padding comes in and it looks like this:

**Comment by zhijiazheng123** [comment]
okay, but from user point of view, if we use  whole screen, the only method to quit navigation view is to slide it to left, right? sometimes user may wrongly consider pressing back key could quit the navigation view, but actually after press back key the whole app quits, how about we only close the drawer when back key pressed?

**Comment by twinone** [comment]
Fixed in 3fa2ffa4a359339ff6eed4f31e73fee62b5562b8

**Pull request closed without merging**
